[package]
name = "zinc-source"
version = "0.2.0-ING-1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc source code representation"

[dependencies]
serde = "1.0"

zinc-const = { path = "../zinc-const" }
