[package]
name = "zinc-compiler"
version = "0.2.0-ING-1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
    "Alexander Movchan <am@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc compiler"

[[bin]]
name = "znc"
path = "src/znc/mod.rs"

[dependencies]
log = "0.4"
structopt = "0.3"
colored = "2.0"

serde = "1.0"
serde_json = "1.0"
num = "0.3"
lazy_static = "1.4"
petgraph = "0.5"

zinc-lexical = { path = "../zinc-lexical" }
zinc-syntax = { path = "../zinc-syntax" }
zinc-manifest = { path = "../zinc-manifest" }
zinc-const = { path = "../zinc-const" }
zinc-math = { path = "../zinc-math" }
zinc-logger = { path = "../zinc-logger" }
zinc-source = { path = "../zinc-source" }
zinc-build = { path = "../zinc-build" }
