[package]
name = "zinc-manifest"
version = "0.2.0-ING-1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc project manifest file"

[dependencies]
failure = "0.1"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

zinc-const = { path = "../zinc-const" }
